schema_version = "1.0.0"

id = "blend_sanitizer"
version = "0.1.0"
name = "Blend Sanitizer"
tagline = 'A tool for removing sensitive data'
maintainer = "Errorbot1122 <errorbid@outlook.com>"
type = "add-on"
tags = ["System", "Development"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

# TODO: Add window-arm (win32 i think) somehow?
platforms = ["windows-x64", "macos-x64", "macos-arm64", "linux-x64", "linux-arm64"]
wheels = [
	"./.wheels/numpy-2.2.6-cp311-cp311-macosx_10_9_x86_64.whl",
	"./.wheels/numpy-2.2.6-cp311-cp311-macosx_11_0_arm64.whl",
	"./.wheels/numpy-2.2.6-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
	"./.wheels/numpy-2.2.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./.wheels/numpy-2.2.6-cp311-cp311-win_amd64.whl",
	"./.wheels/opencv_python-4.12.0.88-cp37-abi3-macosx_13_0_arm64.whl",
	"./.wheels/opencv_python-4.12.0.88-cp37-abi3-macosx_13_0_x86_64.whl",
	"./.wheels/opencv_python-4.12.0.88-cp37-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.whl",
	"./.wheels/opencv_python-4.12.0.88-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
	"./.wheels/opencv_python-4.12.0.88-cp37-abi3-win_amd64.whl",
]

[permissions]
files = "Copy original sanitized files"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".venv/",
  "tmp/",
  "/*.zip",
]
